# docker-compose.yml
services:
  postgres:
    image: postgres:16
    container_name: skytrack_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: skytrack
      POSTGRES_USER: skytrack
      POSTGRES_PASSWORD: skytrack
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mongo:
    image: mongo:latest
    container_name: skytrack_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: skytrack_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - DB_HOST=postgres
      - DB_NAME=skytrack
      - DB_USER=skytrack
      - DB_PASSWORD=skytrack
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: skytrack_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data:
