# docker-compose.yml
services:
  db:
    image: postgres:16
    container_name: skytrack_db
    restart: always
    environment:
      POSTGRES_DB: skytrack_db
      POSTGRES_USER: skytrack_user
      POSTGRES_PASSWORD: skytrack_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: