# Generated by Django 6.0.3 on 2026-04-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('pro', 'Profesional')], default='beginner', max_length=20),
        ),
    ]
