# Generated by Django 6.0.3 on 2026-04-20 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='saved_missions', to=settings.AUTH_USER_MODEL),
        ),
    ]
