# Generated by Django 6.0.3 on 2026-04-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_likes_mission_saves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='saves',
            new_name='saved_by',
        ),
    ]
