# Generated by Django 6.0.3 on 2026-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_rename_saves_mission_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='max_alt_m',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mission',
            name='max_vel_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mission',
            name='visibility',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
