# Generated by Django 6.0.3 on 2026-05-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_mission_max_alt_m_mission_max_vel_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='saved_by',
        ),
        migrations.DeleteModel(
            name='TelemetryPoint',
        ),
    ]
