# Generated by Django 6.0.3 on 2026-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_remove_mission_likes_remove_mission_saved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En curso'), ('completed', 'Completada')], default='completed', max_length=20),
        ),
    ]
